terraform: &terraform
  docker:
    - image: hashicorp/terraform:full

version: 2
jobs:
  build:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: terraform lint
          command: terraform fmt -diff -check -recursive
      - run:
          name: terraform init
          working_directory: environment
          command: terraform init
      - run:
          name: terraform plan
          working_directory: environment
          environment:
            TF_WORKSPACE: master
            TF_VAR_OPG_DOCKER_TAG: dummy_value
          command: terraform plan -input=false -lock=false
workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - master

